# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute
controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /
api_login_check:
    path: /api/login_check


